### ISSUE TITLE
What's your final metrics on the validation of Pascal VOC 2012 ? Thx

### ISSUE THREAD

**Issue by wuyang556** [yiskw713/fastfcn#1]

**Comment by yiskw713** [comment]
Hi, Wuyang9

Actually I did experiments on only my own dataset.
For your information, this is the comparison b/w UNet and Fast FCN on my dataset.

|  | pixel accuracy | mIoU |
|---|---|---|
|U-Net  |91.0  |77.5  |
|Fast FCN  |92.1  |79.2 |

Fast FCN is better than UNet, though UNet also got good scores since my dataset is a little simple and easy.
I hope this helps you. Thanks.

yiskw713

**Comment by wuyang556** [comment]
Thanks for your reply.
